{{-- Loan Deed — table of contents (source PDF pages 2-3). Static page numbers matching the fixed template layout. --}}
@php
    $tocMain = [
        ['1', 'Definitions and interpretation', '1'],
        ['1.1', 'Definitions', '1'],
        ['1.2', 'Interpretation', '4'],
        ['1.3', 'Sole agreement', '5'],
        ['1.4', 'Inconsistency', '5'],
        ['1.5', 'Joint and several liability', '5'],
        ['1.6', 'Neutral interpretation', '5'],
        ['2', 'Loan', '6'],
        ['2.1', 'Advance', '6'],
        ['2.2', 'Use of Loan', '6'],
        ['3', 'Interest', '6'],
        ['3.1', 'Interest accrues', '6'],
        ['3.2', 'Payment of Interest', '6'],
        ['3.3', 'Additional interest', '6'],
        ['3.4', 'Capitalisation of amounts due in default', '6'],
        ['4', 'Conditions precedent to Lender\'s obligations', '7'],
        ['4.1', 'Conditions precedent', '7'],
        ['4.2', 'Non-satisfaction of conditions precedent', '7'],
        ['5', 'Repayment and prepayment', '7'],
        ['5.1', 'Payment of Amount Owing', '7'],
        ['5.2', 'Prepayment', '8'],
        ['5.3', 'Release of Encumbrance', '8'],
        ['6', 'Payments generally', '8'],
        ['6.1', 'Manner of payment', '8'],
        ['6.2', 'Direct Debit Arrangement', '8'],
        ['6.3', 'Grossing up', '8'],
        ['7', 'Security requirements and undertakings', '9'],
        ['7.1', 'Security', '9'],
        ['7.2', 'Negative pledge — no Encumbrances', '9'],
        ['8', 'Events of Default', '9'],
        ['8.1', 'Events occurring', '9'],
        ['8.2', 'Consequences', '10'],
    ];
    $tocSecond = [
        ['9', 'Attorney', '10'],
        ['9.1', 'Appointment', '10'],
        ['9.2', 'General', '10'],
        ['10', 'Representations and warranties', '11'],
        ['10.1', 'By each party', '11'],
        ['10.2', 'By each Obligor', '11'],
        ['10.3', 'By the Borrower', '12'],
        ['10.4', 'No reliance on representations', '12'],
        ['10.5', 'Undertaking', '12'],
        ['10.6', 'Indemnity', '13'],
        ['11', 'Fees and costs', '13'],
        ['11.1', 'Legal Fees', '13'],
        ['11.2', 'Costs', '13'],
        ['12', 'Lender\'s limitation of liability', '13'],
        ['13', 'Confidentiality', '14'],
        ['13.1', 'Mutual agreement', '14'],
        ['13.2', 'Permitted use', '14'],
        ['13.3', 'Return of Confidential Information', '15'],
        ['14', 'Dispute resolution', '15'],
        ['14.1', 'Dispute', '15'],
        ['14.2', 'Restriction on litigation', '15'],
        ['14.3', 'Procedure', '15'],
        ['14.4', 'Place of mediation', '15'],
        ['14.5', 'Application to court', '16'],
        ['14.6', 'Continuing obligations', '16'],
        ['15', 'Notices', '16'],
        ['15.1', 'Method of giving', '16'],
        ['15.2', 'Time of receipt', '16'],
        ['15.3', 'Address for notices', '16'],
        ['16', 'GST', '16'],
        ['16.1', 'Interpretation', '16'],
        ['16.2', 'Inclusive', '16'],
        ['16.3', 'How calculated', '16'],
        ['16.4', 'Payment', '17'],
        ['17', 'Miscellaneous', '17'],
        ['17.1', 'Assignment', '17'],
        ['17.2', 'Amendment', '17'],
        ['17.3', 'Waiver', '17'],
        ['17.4', 'Further assurances', '17'],
        ['17.5', 'Severability', '17'],
        ['17.6', 'Execution and counterparts', '17'],
        ['17.7', 'Indemnities', '17'],
        ['17.8', 'Partial invalidity', '18'],
        ['17.9', 'Set-off', '18'],
        ['17.10', 'Execution by attorney', '18'],
        ['17.11', 'Other obligations', '18'],
        ['18', 'Law and jurisdiction', '18'],
        ['18.1', 'Governing law', '18'],
        ['18.2', 'Submission to jurisdiction', '18'],
        ['19', 'Commercial Transaction and Fairness Acknowledgement', '19'],
        ['20', 'Direct Debit Authority', '19'],
        ['', 'Schedule', '20'],
        ['', 'Schedule 2', '21'],
        ['', 'Schedule 3', '22'],
    ];
@endphp

<div class="deed-page deed-toc">
    <h2 class="deed-toc-heading">Contents</h2>
    @include('shared.loan-deed.toc-entries', ['entries' => $tocMain])
</div>

<div class="deed-page deed-toc">
    @include('shared.loan-deed.toc-entries', ['entries' => $tocSecond])
</div>
